### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by billalxcode**
Fixed error when
1. Image not found
2. File not found
3. Run the app.py file

Add
1. Image predicate type
2. Create a predict_image function in lib/predict.py

### CODE REVIEW

**Comment by salismazaya** [comment]
bisa pull ke dev dulu gak bang? mau di test dulu

**Comment by billalxcode** [comment]
Emng ada branch dev?

**Comment by billalxcode** [comment]
Tak kira gada branch dev wkwk

**Comment by billalxcode** [comment]
Yowes gw bikin PR baru aja tapi PR nya ke branch dev

**Pull request closed without merging**
